// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blogPosts: create.doc("blogPosts", {"api-security-monitoring.mdx": () => import("../content/blog/api-security-monitoring.mdx?collection=blogPosts"), "building-soc-team.mdx": () => import("../content/blog/building-soc-team.mdx?collection=blogPosts"), "cloud-security-monitoring.mdx": () => import("../content/blog/cloud-security-monitoring.mdx?collection=blogPosts"), "hello-world.mdx": () => import("../content/blog/hello-world.mdx?collection=blogPosts"), "implementing-siem-solutions.mdx": () => import("../content/blog/implementing-siem-solutions.mdx?collection=blogPosts"), "incident-response-automation.mdx": () => import("../content/blog/incident-response-automation.mdx?collection=blogPosts"), "machine-learning-threat-detection.mdx": () => import("../content/blog/machine-learning-threat-detection.mdx?collection=blogPosts"), "security-metrics-dashboard.mdx": () => import("../content/blog/security-metrics-dashboard.mdx?collection=blogPosts"), "threat-hunting-techniques.mdx": () => import("../content/blog/threat-hunting-techniques.mdx?collection=blogPosts"), "understanding-soc-platforms.mdx": () => import("../content/blog/understanding-soc-platforms.mdx?collection=blogPosts"), "zero-trust-architecture.mdx": () => import("../content/blog/zero-trust-architecture.mdx?collection=blogPosts"), }),
  docs: create.doc("docs", {"aaatest.mdx": () => import("../content/docs/aaatest.mdx?collection=docs"), "analytics.mdx": () => import("../content/docs/analytics.mdx?collection=docs"), "api-reference.mdx": () => import("../content/docs/api-reference.mdx?collection=docs"), "architecture.mdx": () => import("../content/docs/architecture.mdx?collection=docs"), "best-practices.mdx": () => import("../content/docs/best-practices.mdx?collection=docs"), "deployment.mdx": () => import("../content/docs/deployment.mdx?collection=docs"), "dhdhdfhdfhdfh.mdx": () => import("../content/docs/dhdhdfhdfhdfh.mdx?collection=docs"), "getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "hello-world.mdx": () => import("../content/docs/hello-world.mdx?collection=docs"), "hgjhg.mdx": () => import("../content/docs/hgjhg.mdx?collection=docs"), "incident-management.mdx": () => import("../content/docs/incident-management.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "integrations.mdx": () => import("../content/docs/integrations.mdx?collection=docs"), "jhkjhkh.mdx": () => import("../content/docs/jhkjhkh.mdx?collection=docs"), "ljklkjlkj.mdx": () => import("../content/docs/ljklkjlkj.mdx?collection=docs"), "oussama.mdx": () => import("../content/docs/oussama.mdx?collection=docs"), "sdklksdjklfjds.mdx": () => import("../content/docs/sdklksdjklfjds.mdx?collection=docs"), "test-this.mdx": () => import("../content/docs/test-this.mdx?collection=docs"), "test.mdx": () => import("../content/docs/test.mdx?collection=docs"), "testjh.mdx": () => import("../content/docs/testjh.mdx?collection=docs"), "testjhkjhjk.mdx": () => import("../content/docs/testjhkjhjk.mdx?collection=docs"), "threat-detection.mdx": () => import("../content/docs/threat-detection.mdx?collection=docs"), "vinci.mdx": () => import("../content/docs/vinci.mdx?collection=docs"), "Folder/file.mdx": () => import("../content/docs/Folder/file.mdx?collection=docs"), }),
};
export default browserCollections;